server:
  error:
    whitelabel:
      enabled: false

spring:
  mvc:
    converters:
      preferred-json-mapper: gson
    static-path-pattern: /static/**

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 843307007567-4dhsploof6dmgbqtmqnkltf7ck2v2skp.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

springdoc:
  api-docs:
    path: /docs

  swagger-ui:
    path: /swagger-ui
    display-request-duration: true

  cache:
    disabled: true
  paths-to-match: /api/v1/**
#    todo 기본 에러페이지 추가

app:
  version: 1.0.0
  secret-key: ${JWT_SECRET_KEY}
